apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  PAYPAL_CLIENT_ID: {{ .Values.secrets.paypalClientId | b64enc | quote }}
  PAYPAL_CLIENT_SECRET: {{ .Values.secrets.paypalClientSecret | b64enc | quote }}