apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secrets
type: Opaque
data:
  db-user: dHVfdXN1YXJpbw==      # Codifica tu_usuario en base64
  db-password: dHVfY29udHJhc2XDsWE=  # Codifica tu_contraseña en base64
  jwt-secret: dHVfY2xhdmVfc2VjcmV0YQ==  # Codifica tu_clave_secreta en base64