version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - app-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      USER_MICROSERVICE_URL: ${USER_MICROSERVICE_URL}
      ACCOUNT_MICROSERVICE_URL: ${ACCOUNT_MICROSERVICE_URL}
      ENVELOPE_MICROSERVICE_URL: ${ENVELOPE_MICROSERVICE_URL}
    depends_on:
      - db
    networks:
      - app-network

  envelope-service:
    build: ./envelope-service
    container_name: envelope-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      USER_MICROSERVICE_URL: ${USER_MICROSERVICE_URL}
      ACCOUNT_MICROSERVICE_URL: ${ACCOUNT_MICROSERVICE_URL}
      ENVELOPE_MICROSERVICE_URL: ${ENVELOPE_MICROSERVICE_URL}
    depends_on:
      - db
    networks:
      - app-network

  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
      SECRET_KEY: ${SECRET_KEY}
      USER_MICROSERVICE_URL: ${USER_MICROSERVICE_URL}
      ACCOUNT_MICROSERVICE_URL: ${ACCOUNT_MICROSERVICE_URL}
      ENVELOPE_MICROSERVICE_URL: ${ENVELOPE_MICROSERVICE_URL}
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: